source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'iOS' do
    pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream.git', :branch => 'swift3'
    pod 'SwiftyJSON'
end
